<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname( __DIR__ );
$baseDir   = dirname( $vendorDir );

return [
	'Psr\\Container\\'     => [ $vendorDir . '/psr/container/src' ],
	'Faker\\'              => [ $vendorDir . '/fakerphp/faker/src/Faker' ],
	'Cbx\\Careertoolkit\\' => [ $baseDir . '/includes' ],
];
