<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit660ce0766d71816ac8264ce30cb08817 {
	public static $files = [
		'6e3fae29631ef280660b3cdad06f25a8' => __DIR__ . '/..' . '/symfony/deprecation-contracts/function.php',
	];

	public static $prefixLengthsPsr4 = [
		'P' =>
			[
				'Psr\\Container\\' => 14,
			],
		'F' =>
			[
				'Faker\\' => 6,
			],
		'C' =>
			[
				'Cbx\\Careertoolkit\\' => 15,
			],
	];

	public static $prefixDirsPsr4 = [
		'Psr\\Container\\'     =>
			[
				0 => __DIR__ . '/..' . '/psr/container/src',
			],
		'Faker\\'              =>
			[
				0 => __DIR__ . '/..' . '/fakerphp/faker/src/Faker',
			],
		'Cbx\\Careertoolkit\\' =>
			[
				0 => __DIR__ . '/../..' . '/includes',
			],
	];

	public static $classMap = [
		'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
	];

	public static function getInitializer( ClassLoader $loader ) {
		return \Closure::bind( function () use ( $loader ) {
			$loader->prefixLengthsPsr4 = ComposerStaticInit660ce0766d71816ac8264ce30cb08817::$prefixLengthsPsr4;
			$loader->prefixDirsPsr4    = ComposerStaticInit660ce0766d71816ac8264ce30cb08817::$prefixDirsPsr4;
			$loader->classMap          = ComposerStaticInit660ce0766d71816ac8264ce30cb08817::$classMap;

		}, null, ClassLoader::class );
	}
}
